language: python
python:
 - "3.7"
 
#Blacklist master branch
branches:
  except:
    - master

#Run Project3 branch
branches:
  only:
    - Project3
    
  
# command to run tests
script:
 - python -m unittest test_sprint3